apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      bb: {{ .Values.bb }}
  template:
    metadata:
      labels:
        bb: {{ .Values.bb }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
